use std::ffi::OsStr;
use std::fs;
use std::path::{Path, PathBuf};
use std::process::Command;

use anyhow::{bail, Context, Result};
use clap::Parser;
use rauha_ebpf_common::offsets::{
    object_sha256, offsets_sidecar_path, render_offsets_sidecar, resolve_kernel_offsets,
    ResolvedOffset,
};

#[derive(Parser)]
#[allow(clippy::enum_variant_names)] // Keep the established `build-*` CLI names.
enum Cli {
    /// Build the eBPF programs for rauha-ebpf.
    BuildEbpf {
        /// Build in release mode.
        #[clap(long)]
        release: bool,
    },
}

fn main() -> Result<()> {
    let cli = Cli::parse();
    match cli {
        Cli::BuildEbpf { release } => build_ebpf(release),
    }
}

fn project_root() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .parent()
        .expect("xtask is in project root")
        .to_path_buf()
}

fn target_dir(root: &Path, configured: Option<&OsStr>, fallback: PathBuf) -> PathBuf {
    match configured.map(PathBuf::from) {
        Some(path) if path.is_absolute() => path,
        Some(path) => root.join(path),
        None => fallback,
    }
}

fn configured_target_dir(root: &Path, fallback: PathBuf) -> PathBuf {
    let configured = std::env::var_os("CARGO_TARGET_DIR");
    target_dir(root, configured.as_deref(), fallback)
}

fn build_ebpf(release: bool) -> Result<()> {
    let root = project_root();
    let ebpf_dir = root.join("rauha-ebpf");

    if !ebpf_dir.exists() {
        bail!(
            "rauha-ebpf directory not found at {}. Create it first.",
            ebpf_dir.display()
        );
    }

    let ebpf_target = configured_target_dir(&root, ebpf_dir.join("target"));
    let generated_offsets = generate_ebpf_offsets(&root)?;

    let mut cmd = Command::new("cargo");
    cmd.current_dir(&ebpf_dir)
        .env_remove("RUSTUP_TOOLCHAIN")
        .env("CARGO_TARGET_DIR", &ebpf_target)
        .env("RAUHA_EBPF_OFFSETS", &generated_offsets.source_path)
        // Disable UB checks — the alignment panic intrinsics they emit
        // produce .text.unlikely. functions that the BPF verifier rejects.
        .env("RUSTFLAGS", "-Zub-checks=no -Dwarnings")
        .args([
            "+nightly",
            "build",
            "--target",
            "bpfel-unknown-none",
            "-Z",
            "build-std=core",
            "--features",
            "generated-offsets",
        ]);

    if release {
        cmd.arg("--release");
    }

    let status = cmd.status().context("failed to run cargo build for eBPF")?;
    if !status.success() {
        bail!("eBPF build failed");
    }

    let profile = if release { "release" } else { "debug" };
    let artifact = ebpf_target
        .join("bpfel-unknown-none")
        .join(profile)
        .join("rauha-ebpf");

    let sidecar = write_offsets_sidecar(&artifact, &generated_offsets.offsets)?;

    println!("eBPF object built: {}", artifact.display());
    println!("eBPF offsets sidecar: {}", sidecar.display());
    Ok(())
}

struct GeneratedOffsets {
    source_path: PathBuf,
    offsets: Vec<ResolvedOffset>,
}

fn generate_ebpf_offsets(root: &Path) -> Result<GeneratedOffsets> {
    let btf = Path::new("/sys/kernel/btf/vmlinux");
    if !btf.exists() {
        bail!("cannot build production eBPF object: /sys/kernel/btf/vmlinux is missing");
    }

    let offsets = resolve_kernel_offsets().map_err(anyhow::Error::msg)?;

    let out_dir = configured_target_dir(root, root.join("target")).join("rauha-ebpf-generated");
    fs::create_dir_all(&out_dir)
        .with_context(|| format!("failed to create {}", out_dir.display()))?;
    let source_path = out_dir.join("offsets.rs");

    let mut source =
        String::from("// Generated by `cargo xtask build-ebpf` from /sys/kernel/btf/vmlinux.\n");
    source.push_str("// Do not edit by hand.\n\n");
    for offset in &offsets {
        source.push_str(&format!(
            "pub const {}: usize = {};\n",
            offset.rust_const, offset.offset
        ));
    }

    fs::write(&source_path, source)
        .with_context(|| format!("failed to write {}", source_path.display()))?;

    Ok(GeneratedOffsets {
        source_path,
        offsets,
    })
}

fn write_offsets_sidecar(artifact: &Path, offsets: &[ResolvedOffset]) -> Result<PathBuf> {
    let sidecar = offsets_sidecar_path(artifact);
    let object_hash = object_sha256(artifact).map_err(anyhow::Error::msg)?;
    let manifest = render_offsets_sidecar(&object_hash, offsets);

    fs::write(&sidecar, manifest)
        .with_context(|| format!("failed to write {}", sidecar.display()))?;
    Ok(sidecar)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn relative_target_dir_is_resolved_from_project_root() {
        assert_eq!(
            target_dir(
                Path::new("/repo"),
                Some(OsStr::new("cache")),
                PathBuf::from("unused")
            ),
            PathBuf::from("/repo/cache")
        );
    }
}
